In [1]:
import tensorflow as tf
print(tf.__version__)

1.14.0


In [2]:
from tensorflow.python.client import device_lib
print(device_lib.list_local_devices())

[name: "/device:CPU:0"
device_type: "CPU"
memory_limit: 268435456
locality {
}
incarnation: 11934981142396300823
, name: "/device:GPU:0"
device_type: "GPU"
memory_limit: 3146173646
locality {
  bus_id: 1
  links {
  }
}
incarnation: 3030392310112645876
physical_device_desc: "device: 0, name: GeForce GTX 1050 Ti, pci bus id: 0000:01:00.0, compute capability: 6.1"
]


In [3]:
tf.test.is_gpu_available()

True

In [5]:
tf.test.gpu_device_name()

'/device:GPU:0'

In [6]:
import numpy as np

In [7]:
g=tf.Graph()

In [8]:
with g.as_default():
    #t1=tf.constant(np.pi)
    t1=tf.constant([[2,3,4],[1,2,3]])
    print(t1.graph)
    print(t1.graph is tf.get_default_graph())
    print(t1)
    print(t1.dtype)
    s1=t1.get_shape()
    print(s1)
    r1=tf.rank(t1)
    print(r1)

True
Tensor("Const:0", shape=(2, 3), dtype=int32)
<dtype: 'int32'>
(2, 3)
Tensor("Rank:0", shape=(), dtype=int32)


In [9]:
with tf.Session(graph=g) as sess:
    print('Ranks:',r1.eval())
    print('Tensor t1:',sess.run(t1))

Ranks: 2
Tensor t1: [[2 3 4]
 [1 2 3]]


# to implement z=2*(a-b)+c

In [9]:
#create graph and then create whole nodes
with g.as_default():
    #t1=tf.constant(np.pi)
    a=tf.constant(1)
    b=tf.constant(2)
    c=tf.constant(3)
    z=2*(a-b)+c

In [10]:
#run throuhg session
with tf.Session(graph=g) as sess:
    print('value:',z.eval())
    #print('value:',sess.run(z))

value: 1


# type casting of variable

In [11]:
x=tf.constant([2,3,4],name='x',dtype=tf.float32)
print(x.dtype)
y=tf.cast(x,tf.int64)
print(y.dtype)

<dtype: 'float32'>
<dtype: 'int64'>


In [12]:
with g.as_default():
    #t1=tf.constant(np.pi)
    a=tf.constant(10,name='x',dtype=tf.float32)
    print(a.dtype)
    b=tf.cast(a,tf.int32)
    print(b.dtype)

<dtype: 'float32'>
<dtype: 'int32'>


In [14]:
with tf.Session(graph=g) as sess:
    print('value:',a.eval())
    print('value:',sess.run(b))

value: 10.0
value: 10


# write a program to create a tensor of 2D with their shape and rank through interractive session

In [10]:
sess=tf.InteractiveSession()
a=tf.zeros(shape=(2,5))
#a=tf.ones(shape=(10,2,3),dtype=tf.int32)
print(a.get_shape())
print(a.eval())
print('Rank:',sess.run(tf.rank(a)))
sess.close()

(2, 5)
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Rank: 2


In [15]:
sess=tf.InteractiveSession()
a=tf.constant(1)
b=tf.constant(2)
c=tf.constant(3)
z=2*(a-b)+c
print(z.eval())
sess.close()

1


# wap to implement matrix multiplication with vector A(3*3) x(3,1)

In [6]:
sess=tf.InteractiveSession()
a=tf.ones(shape=(3,3),dtype=tf.int32)
print(a.eval())

x=tf.constant([1,2,3])
print(x.eval())
print(x.get_shape(),a.get_shape())

#when only below code is run then it shows error
x1=tf.expand_dims(x,1)   #we have to tell the dimension explicitly
print(x1.get_shape())
#ValueError: Shape must be rank 2 but is rank 1 for 'MatMul' (op: 'MatMul') with input shapes: [3,3], [3].
b=tf.matmul(a,x1)
print(b.eval())
sess.close()

[[1 1 1]
 [1 1 1]
 [1 1 1]]
[1 2 3]
(3,) (3, 3)
(3, 1)
[[6]
 [6]
 [6]]


# Name and Name_scope

In [3]:
sess=tf.InteractiveSession()
a=tf.ones(shape=(3,3),name='a')
b=tf.ones(shape=(3,3),name='a')
c=tf.ones(shape=(3,3),name='a')
print(a.name)
print(b.name)
print(c.name)
with tf.name_scope('NetA'):
    a=tf.zeros(shape=(3,3),name='a')
    b=tf.zeros(shape=(3,3),name='a')
    print(a.name)
    print(b.name)
#print(a.eval())
sess.close()

a:0
a_1:0
a_2:0
NetA/a:0
NetA/a_1:0


In [2]:
import tensorflow as tf
g= tf.Graph()

with g.as_default():
    with tf.variable_scope('net_A'):
        with tf.variable_scope('layer-1'):
            w1= tf.Variable(tf.random_normal(shape=(10,4)),
                       name='weights')
            w2= tf.Variable(tf.random_normal(shape=(10,14)),
                       name='weights')
        with tf.variable_scope('layer-2'):
            w3= tf.Variable(tf.random_normal(shape=(20,14)),
                       name='weights')
    print(w1)
    print(w2)
    print(w3)

<tf.Variable 'net_A/layer-1/weights:0' shape=(10, 4) dtype=float32_ref>
<tf.Variable 'net_A/layer-1/weights_1:0' shape=(10, 14) dtype=float32_ref>
<tf.Variable 'net_A/layer-2/weights:0' shape=(20, 14) dtype=float32_ref>
